  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    volumes:
    - "./config:/mosquitto/config"
    - "./log:/mosquitto/log"
    - "./data:/mosquitto/data"
    restart: always
    ports:
    - "1883:1883" 
