  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    user: "${UID}:${GID}"
    volumes:
    - "./config:/mosquitto/config"
    - "./log:/mosquitto/log"
    - "./data:/mosquitto/data"
    - "./cert:/mosquitto/cert"
    restart: always
    ports:
    - "1883:1883"
    - "8883:8883" 
    - "9001:9001"
