  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    volumes:
    - "./config:/mosquitto/config"
    - "./log:/mosquitto/log"
    - "./data:/mosquitto/data"
    - "./cert:/mosquitto/cert"
    restart: always
    ports:
    - "8883:8883" 
